import React, { useId, useState } from 'react';
import { ArrowRight, Check, ChevronDown, ClipboardList, FileCheck2, ShieldCheck, Stethoscope } from 'lucide-react';
import { DemoNote } from '../../components/health/HealthPrimitives';
import { demoClaims, demoPolicy, estimateCoverage, formatRupees } from '../../data/healthExperience';

export function InsuranceHub({ onFindCare }: { onFindCare: () => void }) {
  const [view, setView] = useState<'coverage' | 'claims' | 'estimate'>('coverage');
  const [bill, setBill] = useState('45000');
  const [exclusions, setExclusions] = useState('2850');
  const fieldId = useId();
  const estimate = bill.trim() && exclusions.trim() ? estimateCoverage(Number(bill), Number(exclusions), demoPolicy) : null;
  return <div className="health-experience health-workspace health-enter">
    <section className="health-overview-welcome"><div><span className="health-eyebrow">COVER, WITH A LITTLE MORE CLARITY</span><h2>Your insurance hub.</h2><p>Understand benefits, follow claims, and plan for care costs.</p></div><DemoNote>Demo policy · no active insurance connection</DemoNote></section>
    <div className="health-insurance-layout">
      <section className="health-policy-card"><div className="health-row"><span className="health-policy-brand"><ShieldCheck size={23} /> studentkare</span><span className="health-policy-tag">SAMPLE PLAN</span></div><div><span className="health-eyebrow">STUDENT GROUP HEALTH COVER</span><h3>{demoPolicy.name}</h3><div className="health-policy-value">{formatRupees(demoPolicy.sumInsured)}</div><span className="health-small">Annual sum insured</span></div><div className="health-policy-footer"><div><span>ILLUSTRATIVE COVER PERIOD</span><strong>{demoPolicy.period}</strong></div><ShieldCheck size={44} strokeWidth={1} /></div></section>
      <section className="health-card health-benefits-summary"><span className="health-eyebrow">UNDERSTAND THE BASICS</span><h3>Your cover, explained.</h3><div className="health-row"><span>Available cover in this example</span><strong>{formatRupees(demoPolicy.remainingCover)}</strong></div><div className="health-row"><span>Sample co-pay</span><strong>{demoPolicy.copayPercent}%</strong></div><div className="health-row"><span>Claims in this demo</span><strong>{demoClaims.length}</strong></div><p>These are illustrative benefits, not a purchased policy. Actual cover, waiting periods, and network eligibility depend on your insurer's policy wording.</p></section>
    </div>
    <div className="health-hub-tabs" aria-label="Insurance sections">{[{ id: 'coverage' as const, label: 'Coverage & benefits', icon: ShieldCheck }, { id: 'claims' as const, label: 'Track claims', icon: ClipboardList }, { id: 'estimate' as const, label: 'Cost estimator', icon: FileCheck2 }].map(({ id, label, icon: Icon }) => <button key={id} aria-pressed={view === id} onClick={() => setView(id)}><Icon size={17} />{label}</button>)}</div>
    <div key={view} className="health-enter">
      {view === 'coverage' && <div className="health-overview-grid"><section className="health-card"><h3>What this sample plan includes</h3><div className="health-benefit-list">{[{ title: 'Inpatient hospitalisation', detail: 'Eligible hospital treatment, subject to the annual sum insured.' }, { title: 'Day-care procedures', detail: 'Listed procedures that do not require a 24-hour admission.' }, { title: 'Pre- and post-hospitalisation', detail: 'Related medical expenses within the policy-defined time window.' }].map(item => <div key={item.title}><span className="health-icon health-icon-mint"><Check size={17} /></span><div><strong>{item.title}</strong><p>{item.detail}</p></div></div>)}</div></section><section className="health-card"><h3>Before you book care</h3><p>Check the network, room-rent limits, waiting periods, and exclusions in your policy. Cashless care requires insurer authorisation.</p><details className="health-insurance-faq"><summary>What does co-pay mean? <ChevronDown size={16} /></summary><p>Co-pay is your share of an eligible medical bill. With a 10% co-pay, you pay ₹1,000 of a ₹10,000 eligible bill, before any other limits or exclusions.</p></details><details className="health-insurance-faq"><summary>What should I prepare for a claim? <ChevronDown size={16} /></summary><p>Keep your itemised bill, payment receipt, consultation or discharge summary, and relevant reports. Your insurer may request additional documents.</p></details><button className="health-text-button" onClick={onFindCare}><Stethoscope size={16} />Explore the care directory <ArrowRight size={15} /></button></section></div>}
      {view === 'claims' && <section className="health-card"><div className="health-row"><div><h3>Every step, a little clearer.</h3><p>Expand a sample claim to see what happens next.</p></div><DemoNote>Illustrative claims</DemoNote></div><div className="health-claim-list">{demoClaims.map(claim => <details key={claim.id} className="health-claim"><summary><span className="health-icon health-icon-brand"><FileCheck2 size={20} /></span><span><strong>{claim.title}</strong><small>{claim.date}</small></span><span className="health-claim-amount">{formatRupees(claim.amount)}</span><span className={`health-claim-status ${claim.stage === 0 ? 'needs-action' : ''}`}>{claim.status}</span><ChevronDown size={17} /></summary><div className="health-claim-detail"><ol className="health-claim-steps">{['Documents', 'In review', 'Decision'].map((step, index) => <li key={step} aria-current={index === claim.stage ? 'step' : undefined} className={index <= claim.stage ? 'is-active' : ''}><span>{index < claim.stage ? <Check size={12} /> : index + 1}</span>{step}</li>)}</ol><p>{claim.description}</p><span className="health-small health-muted">This is a workflow preview. No claim has been submitted to an insurer.</span></div></details>)}</div></section>}
      {view === 'estimate' && <div className="health-overview-grid"><section className="health-card"><span className="health-eyebrow">PLAN WITH MORE PERSPECTIVE</span><h3>What might you pay?</h3><p>Adjust the bill and exclusions to see how this sample plan works.</p><label className="health-field" htmlFor={`${fieldId}-bill`}>Estimated medical bill (₹)<input id={`${fieldId}-bill`} type="number" min="0" step="0.01" inputMode="decimal" value={bill} onChange={event => setBill(event.target.value)} aria-invalid={!estimate} aria-describedby={!estimate ? `${fieldId}-error` : undefined} /></label><label className="health-field" htmlFor={`${fieldId}-excluded`}>Non-covered expenses (₹)<input id={`${fieldId}-excluded`} type="number" min="0" step="0.01" inputMode="decimal" value={exclusions} onChange={event => setExclusions(event.target.value)} aria-invalid={!estimate} aria-describedby={!estimate ? `${fieldId}-error` : undefined} /></label>{!estimate && <p id={`${fieldId}-error`} className="health-field-error" role="alert">Enter valid non-negative amounts. Non-covered expenses cannot exceed the bill.</p>}<p className="health-small">Assumptions: {demoPolicy.copayPercent}% co-pay after exclusions, with {formatRupees(demoPolicy.remainingCover)} remaining cover. Other policy limits are not included.</p></section><section className="health-card health-estimate-result" aria-live="polite" aria-atomic="true"><ShieldCheck size={31} /><span className="health-eyebrow">YOUR ILLUSTRATIVE BREAKDOWN</span><h3>Estimated insurer share</h3><div className="health-estimate-amount">{estimate ? formatRupees(estimate.covered) : '—'}</div><div className="health-estimate-lines"><div><span>Non-covered expenses</span><strong>{estimate ? formatRupees(estimate.excluded) : '—'}</strong></div><div><span>Your co-pay ({demoPolicy.copayPercent}%)</span><strong>{estimate ? formatRupees(estimate.copay) : '—'}</strong></div><div><span>Above remaining cover</span><strong>{estimate ? formatRupees(estimate.limitExcess) : '—'}</strong></div><div className="health-estimate-total"><span>Your estimated out-of-pocket</span><strong>{estimate ? formatRupees(estimate.outOfPocket) : '—'}</strong></div></div><p className="health-small">An illustration, not an approval or quote. Your insurer determines the payable amount under your actual policy.</p></section></div>}
    </div>
  </div>;
}
