#!/usr/bin/env node
// Generates code artefacts from design/tokens/studentkare.tokens.json — the single
// source of truth. Run `npm run tokens:build` after editing the JSON.
// `npm run tokens:check` fails if the generated files are out of date (use in CI).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const SRC = resolve(root, 'design/tokens/studentkare.tokens.json');
const OUT_TS = resolve(root, 'src/theme/tokens/generated/skTokens.ts');
const OUT_CSS = resolve(root, 'src/theme/tokens/generated/sk-tokens.css');
const HEADER = '// GENERATED by scripts/tokens/build-tokens.mjs from design/tokens/studentkare.tokens.json.\n// Do not edit by hand — edit the JSON and run `npm run tokens:build`.\n';

const json = JSON.parse(readFileSync(SRC, 'utf8'));
const camel = (k) => k.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const leaves = (group) => Object.fromEntries(Object.entries(group).filter(([k, v]) => !k.startsWith('$') && v && typeof v === 'object' && '$value' in v).map(([k, v]) => [camel(k), v.$value]));
const px = (v) => (typeof v === 'string' && v.endsWith('px') ? Number(v.slice(0, -2)) : v);
const pxMap = (o) => Object.fromEntries(Object.entries(o).map(([k, v]) => [k, px(v)]));
const bezier = (a) => `cubic-bezier(${a.join(', ')})`;
const shadowCss = (s) => `${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} ${s.color}`;

const t = {
  color: { light: leaves(json.color.light), dark: leaves(json.color.dark) },
  font: {
    family: Object.fromEntries(Object.entries(leaves(json.font.family)).map(([k, v]) => [k, v.map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(', ')])),
    size: pxMap(leaves(json.font.size)),
    weight: leaves(json.font.weight),
    lineHeight: leaves(json.font['line-height']),
  },
  space: pxMap(Object.fromEntries(Object.entries(json.space).filter(([k]) => !k.startsWith('$')).map(([k, v]) => [/^\d/.test(k) ? `s${k}` : camel(k), v.$value]))),
  radius: pxMap(leaves(json.radius)),
  size: pxMap(leaves(json.size)),
  shadow: Object.fromEntries(Object.entries(leaves(json.shadow)).map(([k, v]) => [k, shadowCss(v)])),
  motion: {
    duration: Object.fromEntries(Object.entries(leaves(json.motion.duration)).map(([k, v]) => [k, Number(String(v).replace('ms', ''))])),
    easing: Object.fromEntries(Object.entries(leaves(json.motion.easing)).map(([k, v]) => [k, bezier(v)])),
  },
  contrastPairs: json['contrast-pairs'].$value.map(([fg, bg, min]) => ({ fg: camel(fg), bg: camel(bg), min })),
};

const ts = `${HEADER}
export const skTokens = ${JSON.stringify(t, null, 2)} as const;

export type SkColorRole = keyof typeof skTokens.color.light;
export type SkColorScheme = keyof typeof skTokens.color;
`;

const kebab = (k) => k.replace(/^s(\d)/, '$1').replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`).replace(/([a-z])(\d)/g, '$1-$2');
const vars = (obj, prefix, unit = '') => Object.entries(obj).map(([k, v]) => `  --sk-${prefix}-${kebab(k)}: ${v}${typeof v === 'number' ? unit : ''};`).join('\n');
const css = `/* GENERATED by scripts/tokens/build-tokens.mjs — edit design/tokens/studentkare.tokens.json instead. */
:root {
${vars(t.color.light, 'color')}
${vars(t.font.family, 'font')}
${vars(t.font.size, 'text', 'px')}
${vars(t.space, 'space', 'px')}
${vars(t.radius, 'radius', 'px')}
${vars(t.size, 'size', 'px')}
${vars(t.shadow, 'shadow')}
${vars(t.motion.duration, 'duration', 'ms')}
${vars(t.motion.easing, 'ease')}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${vars(t.color.dark, 'color').replace(/^/gm, '  ')}
  }
}
:root[data-theme="dark"] {
${vars(t.color.dark, 'color')}
}
@media (prefers-reduced-motion: reduce) {
  :root { --sk-duration-fast: 0ms; --sk-duration-base: 0ms; --sk-duration-sheet: 0ms; }
}
`;

const check = process.argv.includes('--check');
const outputs = [[OUT_TS, ts], [OUT_CSS, css]];
if (check) {
  const stale = outputs.filter(([p, body]) => { try { return readFileSync(p, 'utf8') !== body; } catch { return true; } }).map(([p]) => p.replace(`${root}/`, ''));
  if (stale.length) { console.error(`Design tokens are out of date: ${stale.join(', ')}\nRun: npm run tokens:build`); process.exit(1); }
  console.log('Design tokens are up to date.');
} else {
  for (const [p, body] of outputs) { mkdirSync(dirname(p), { recursive: true }); writeFileSync(p, body); }
  console.log(`Wrote ${outputs.map(([p]) => p.replace(`${root}/`, '')).join(', ')}`);
}
