import { registerModule } from '@/core/routing';
import type { FeatureModule, FeatureRoute } from '@/core/routing';
import type { AccountRole } from '@/data/workflowTypes';

const hasRole = (...roles: AccountRole[]) => (role: AccountRole | null): boolean => (role ? roles.includes(role) : false);

const workspacePaths: { path: string; access?: (role: AccountRole | null) => boolean; public?: boolean }[] = [
  { path: '/health' },
  { path: '/profile' },
  { path: '/billing' },
  { path: '/digital-id' },
  { path: '/records' },
  { path: '/vault' },
  { path: '/insurance' },
  { path: '/orders' },
  { path: '/appointments' },
  { path: '/medications' },
  { path: '/health-camp' },
  { path: '/camp' },
  { path: '/notifications' },
  { path: '/care-navigator' },
  { path: '/preventive-care' },
  { path: '/report-reviews', access: hasRole('NMC_DOCTOR') },
  { path: '/earnings', access: hasRole('NMC_DOCTOR') },
  { path: '/chronic', access: hasRole('NMC_DOCTOR') },
  { path: '/support' },
  { path: '/help' },
  { path: '/movement' },
  { path: '/wellness' },
  { path: '/campus-wellness', access: hasRole('CAMPUS_ADMIN', 'SUPER_ADMIN') },
  { path: '/devices' },
  { path: '/clinical-notes', access: hasRole('NMC_DOCTOR', 'SUPER_ADMIN') },
  { path: '/prescriptions' },
  { path: '/ayush' },
  { path: '/clinical-review', access: hasRole('NMC_DOCTOR', 'SUPER_ADMIN') },
  { path: '/dispensing', public: true },
  { path: '/dispense-register', public: true },
  { path: '/vendor-dispense-register', public: true },
  { path: '/lab-queue', public: true },
  { path: '/vendor-lab-queue', public: true },
  { path: '/verify', access: hasRole('VENDOR', 'SUPER_ADMIN') },
  { path: '/catalogue', access: hasRole('VENDOR', 'SUPER_ADMIN') },
  { path: '/run-sheet', access: hasRole('VENDOR', 'SUPER_ADMIN') },
  { path: '/lab-collection', access: hasRole('VENDOR', 'SUPER_ADMIN') },
  { path: '/cold-chain', access: hasRole('VENDOR', 'SUPER_ADMIN') },
  { path: '/lab-cold-chain', access: hasRole('VENDOR', 'SUPER_ADMIN') },
  { path: '/returns', access: hasRole('VENDOR', 'SUPER_ADMIN') },
  { path: '/vendor-returns', access: hasRole('VENDOR', 'SUPER_ADMIN') },
  { path: '/handover', public: true },
  { path: '/vendor-handover', public: true },
  { path: '/substitutions', public: true },
  { path: '/vendor-substitutions', public: true },
  { path: '/reorder', public: true },
  { path: '/vendor-reorder', public: true },
  { path: '/camp-intake', public: true },
  { path: '/vendor-camp-intake', public: true },
  { path: '/settlement', public: true },
  { path: '/settlements', public: true },
  { path: '/vendor-settlement', public: true },
  { path: '/performance', public: true },
  { path: '/vendor-console', public: true },
  { path: '/console', public: true },
  { path: '/rx-review', public: true },
  { path: '/vendor-rx-review', public: true },
  { path: '/staff', public: true },
  { path: '/partner-staff', public: true },
  { path: '/vendor-staff', public: true },
  { path: '/staff-roles', public: true },
  { path: '/admin', access: hasRole('SUPER_ADMIN') },
  { path: '/admin/billing', access: hasRole('SUPER_ADMIN') },
  { path: '/admin/catalog', access: hasRole('SUPER_ADMIN') },
  { path: '/admin/accounts', access: hasRole('SUPER_ADMIN') },
  { path: '/admin/requests', access: hasRole('SUPER_ADMIN') },
  { path: '/admin/support', access: hasRole('SUPER_ADMIN') },
  { path: '/admin/audit', access: hasRole('SUPER_ADMIN') },
  { path: '/admin/integrations', access: hasRole('SUPER_ADMIN') },
  { path: '/admin/telemetry', access: hasRole('SUPER_ADMIN') },
  { path: '/admin/knowledge', access: hasRole('SUPER_ADMIN') },
  { path: '/admin/intake', access: hasRole('SUPER_ADMIN') },
  { path: '/admin/preventive', access: hasRole('SUPER_ADMIN') },
  { path: '/admin/activity', access: hasRole('SUPER_ADMIN') },
  { path: '/vendor', access: hasRole('VENDOR') },
  { path: '/clinician', access: hasRole('NMC_DOCTOR') },
  { path: '/campus', access: hasRole('CAMPUS_ADMIN', 'STUDENT', 'SUPER_ADMIN') },
  { path: '/campus-access-requests', access: hasRole('CAMPUS_ADMIN', 'STUDENT', 'SUPER_ADMIN') },
  { path: '/campus-break-glass', access: hasRole('CAMPUS_ADMIN', 'STUDENT', 'SUPER_ADMIN') },
];

const routes: FeatureRoute[] = [
  { path: '/pricing', public: true, load: () => import('@/screens/billing/PricingScreen').then((m) => ({ default: m.PricingScreen })) },
  ...workspacePaths.map(({ path, access, public: isPublic }) => ({
    path,
    access,
    public: isPublic,
    load: () => import('./screens/WorkspaceRouteScreen').then((m) => ({ default: m.WorkspaceRouteScreen })),
  })),
];

export const healthModule: FeatureModule = {
  id: 'health',
  title: 'Student Health Workspace',
  basePath: '/',
  routes,
};

registerModule(healthModule);
