"""initial tables

Revision ID: 999415fc9941
Revises: 
Create Date: 2026-09-09 01:23:31.599616

"""
from alembic import op
import sqlalchemy as sa


revision = '999415fc9941'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_phone'), 'app_users', ['phone'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('actor_name', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('break_glass_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('requested_by_admin_id', sa.String(), nullable=False),
    sa.Column('reason_category', sa.String(), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('dual_approver_admin_id', sa.String(), nullable=False),
    sa.Column('sensitive_category', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_health_findings',
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('autofixable', sa.Boolean(), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('blast_radius', sa.String(), nullable=False),
    sa.Column('proposed_fix', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('verification_method', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('fingerprint')
    )
    op.create_table('department_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plane', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('kill_switch_active', sa.Boolean(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('active_seats', sa.Integer(), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('abdm_facility_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('joined_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenants')
    op.drop_table('department_states')
    op.drop_table('code_health_findings')
    op.drop_table('break_glass_sessions')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_app_users_phone'), table_name='app_users')
    op.drop_table('app_users')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
