"""add active workflow schema

Revision ID: fe83ff8b6dc6
Revises: 999415fc9941
Create Date: 2026-09-13 21:23:16.395793

"""
import sqlalchemy as sa

from alembic import op

revision = 'fe83ff8b6dc6'
down_revision = '999415fc9941'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(length=254), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_accounts_identifier'), 'care_accounts', ['identifier'], unique=True)
    op.create_table('care_agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=False),
    sa.Column('finished_at', sa.Float(), nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_agent_runs_job_key'), 'care_agent_runs', ['job_key'], unique=False)
    op.create_table('care_articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tag', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('read_time', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_followup_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('resolved_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_followup_tasks_account_id'), 'care_followup_tasks', ['account_id'], unique=False)
    op.create_index(op.f('ix_care_followup_tasks_order_id'), 'care_followup_tasks', ['order_id'], unique=False)
    op.create_table('care_health_camps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_home_content',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('eyebrow', sa.String(length=80), nullable=False),
    sa.Column('body', sa.String(length=4000), nullable=False),
    sa.Column('summary', sa.String(length=400), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target', sa.String(length=40), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('care_knowledge_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('content', sa.String(length=4000), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_otp_challenges',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('identifier', sa.String(length=254), nullable=False),
    sa.Column('intent', sa.String(length=12), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_care_otp_challenges_identifier'), 'care_otp_challenges', ['identifier'], unique=False)
    op.create_table('care_outbox_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('sent_at', sa.Float(), nullable=False),
    sa.Column('read_at', sa.Float(), nullable=False),
    sa.Column('last_error', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_outbox_events_account_id'), 'care_outbox_events', ['account_id'], unique=False)
    op.create_index(op.f('ix_care_outbox_events_dedupe_key'), 'care_outbox_events', ['dedupe_key'], unique=True)
    op.create_table('care_rate_buckets',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_care_rate_buckets_expires_at'), 'care_rate_buckets', ['expires_at'], unique=False)
    op.create_table('care_reviewed_benefits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_scheduled_jobs',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.Float(), nullable=False),
    sa.Column('next_run_at', sa.Float(), nullable=False),
    sa.Column('last_status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('care_signup_grants',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('identifier', sa.String(length=254), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('csrf_token', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('care_system_settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('care_workflow_audit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_workflow_audit_actor_id'), 'care_workflow_audit', ['actor_id'], unique=False)
    op.create_index(op.f('ix_care_workflow_audit_created_at'), 'care_workflow_audit', ['created_at'], unique=False)
    op.create_table('care_camp_attendances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('camp_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('checked_in', sa.Boolean(), nullable=False),
    sa.Column('completed_stations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.ForeignKeyConstraint(['camp_id'], ['care_health_camps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camp_id', 'account_id')
    )
    op.create_index(op.f('ix_care_camp_attendances_account_id'), 'care_camp_attendances', ['account_id'], unique=False)
    op.create_index(op.f('ix_care_camp_attendances_camp_id'), 'care_camp_attendances', ['camp_id'], unique=False)
    op.create_table('care_campus_verifications',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('university', sa.String(length=160), nullable=False),
    sa.Column('roll_number', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('verified_by', sa.String(), nullable=False),
    sa.Column('verified_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('care_catalog',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('pack', sa.String(length=160), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('mrp_paise', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('requires_prescription', sa.Boolean(), nullable=False),
    sa.Column('preparation', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_catalog_provider_id'), 'care_catalog', ['provider_id'], unique=False)
    op.create_table('care_deletion_requests',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('requested_at', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('processed_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('care_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_documents_account_id'), 'care_documents', ['account_id'], unique=False)
    op.create_table('care_encounter_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('appointment_id', sa.String(), nullable=False),
    sa.Column('subjective', sa.String(length=2000), nullable=False),
    sa.Column('objective', sa.String(length=2000), nullable=False),
    sa.Column('assessment', sa.String(length=2000), nullable=False),
    sa.Column('plan', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_encounter_notes_account_id'), 'care_encounter_notes', ['account_id'], unique=False)
    op.create_index(op.f('ix_care_encounter_notes_appointment_id'), 'care_encounter_notes', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_care_encounter_notes_patient_id'), 'care_encounter_notes', ['patient_id'], unique=False)
    op.create_table('care_exercise_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(length=80), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'client_id')
    )
    op.create_index(op.f('ix_care_exercise_sessions_account_id'), 'care_exercise_sessions', ['account_id'], unique=False)
    op.create_table('care_health_camp_stations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('camp_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['care_health_camps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_health_camp_stations_camp_id'), 'care_health_camp_stations', ['camp_id'], unique=False)
    op.create_table('care_medication_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('dosage', sa.String(length=120), nullable=False),
    sa.Column('frequency', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_medication_plans_account_id'), 'care_medication_plans', ['account_id'], unique=False)
    op.create_table('care_notification_preferences',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminders_enabled', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=40), nullable=False),
    sa.Column('quiet_start', sa.String(length=5), nullable=False),
    sa.Column('quiet_end', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('care_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('total_paise', sa.Integer(), nullable=False),
    sa.Column('delivery', sa.JSON(), nullable=False),
    sa.Column('requested_slot', sa.String(length=40), nullable=False),
    sa.Column('payment_status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_care_orders_account_id'), 'care_orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_care_orders_created_at'), 'care_orders', ['created_at'], unique=False)
    op.create_table('care_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('insurer', sa.String(length=100), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('sum_insured', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_policies_account_id'), 'care_policies', ['account_id'], unique=False)
    op.create_table('care_preferences',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('saved_exercises', sa.JSON(), nullable=False),
    sa.Column('completed_tasks', sa.JSON(), nullable=False),
    sa.Column('task_date', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('care_readings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('metric', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_readings_account_id'), 'care_readings', ['account_id'], unique=False)
    op.create_index(op.f('ix_care_readings_metric'), 'care_readings', ['metric'], unique=False)
    op.create_index(op.f('ix_care_readings_recorded_at'), 'care_readings', ['recorded_at'], unique=False)
    op.create_table('care_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('csrf_token', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_care_sessions_account_id'), 'care_sessions', ['account_id'], unique=False)
    op.create_index(op.f('ix_care_sessions_expires_at'), 'care_sessions', ['expires_at'], unique=False)
    op.create_table('care_support_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_support_requests_account_id'), 'care_support_requests', ['account_id'], unique=False)
    op.create_table('care_availability_slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('catalog_item_id', sa.String(), nullable=False),
    sa.Column('slot_start', sa.String(length=40), nullable=False),
    sa.Column('slot_end', sa.String(length=40), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('booked', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['care_catalog.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_availability_slots_catalog_item_id'), 'care_availability_slots', ['catalog_item_id'], unique=False)
    op.create_index(op.f('ix_care_availability_slots_provider_id'), 'care_availability_slots', ['provider_id'], unique=False)
    op.create_table('care_claim_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(length=160), nullable=False),
    sa.Column('service', sa.String(length=160), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['care_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_claim_requests_account_id'), 'care_claim_requests', ['account_id'], unique=False)
    op.create_index(op.f('ix_care_claim_requests_policy_id'), 'care_claim_requests', ['policy_id'], unique=False)
    op.create_table('care_document_intake',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('extractor', sa.String(length=40), nullable=False),
    sa.Column('draft', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('processed_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['care_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_document_intake_account_id'), 'care_document_intake', ['account_id'], unique=False)
    op.create_index(op.f('ix_care_document_intake_document_id'), 'care_document_intake', ['document_id'], unique=False)
    op.create_table('care_medication_doses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('dose_date', sa.String(length=10), nullable=False),
    sa.Column('dose_time', sa.String(length=8), nullable=False),
    sa.Column('taken_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['care_medication_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'dose_date', 'dose_time')
    )
    op.create_index(op.f('ix_care_medication_doses_account_id'), 'care_medication_doses', ['account_id'], unique=False)
    op.create_index(op.f('ix_care_medication_doses_plan_id'), 'care_medication_doses', ['plan_id'], unique=False)
    op.create_table('care_order_lines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['care_catalog.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['care_orders.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_order_lines_order_id'), 'care_order_lines', ['order_id'], unique=False)
    op.create_index(op.f('ix_care_order_lines_provider_id'), 'care_order_lines', ['provider_id'], unique=False)
    op.create_table('care_payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_ref', sa.String(length=120), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('settled_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['care_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_payments_idempotency_key'), 'care_payments', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_care_payments_order_id'), 'care_payments', ['order_id'], unique=False)
    op.create_table('care_record_shares',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('clinician_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('granted_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('last_viewed_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['care_accounts.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['care_documents.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_record_shares_clinician_id'), 'care_record_shares', ['clinician_id'], unique=False)
    op.create_index(op.f('ix_care_record_shares_document_id'), 'care_record_shares', ['document_id'], unique=False)
    op.create_index(op.f('ix_care_record_shares_owner_id'), 'care_record_shares', ['owner_id'], unique=False)
    op.create_table('care_appointments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('catalog_item_id', sa.String(), nullable=False),
    sa.Column('slot_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['care_accounts.id'], ),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['care_catalog.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['care_accounts.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['care_availability_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_appointments_account_id'), 'care_appointments', ['account_id'], unique=False)
    op.create_index(op.f('ix_care_appointments_catalog_item_id'), 'care_appointments', ['catalog_item_id'], unique=False)
    op.create_index(op.f('ix_care_appointments_provider_id'), 'care_appointments', ['provider_id'], unique=False)
    op.create_index(op.f('ix_care_appointments_slot_id'), 'care_appointments', ['slot_id'], unique=False)
    op.create_table('care_intake_review_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('intake_id', sa.String(), nullable=False),
    sa.Column('field', sa.String(length=60), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['care_document_intake.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_intake_review_items_intake_id'), 'care_intake_review_items', ['intake_id'], unique=False)
    op.create_table('care_consultation_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('appointment_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('student_joined_at', sa.Float(), nullable=False),
    sa.Column('provider_joined_at', sa.Float(), nullable=False),
    sa.Column('ended_at', sa.Float(), nullable=False),
    sa.Column('signal_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['care_appointments.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['care_accounts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['care_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_consultation_sessions_appointment_id'), 'care_consultation_sessions', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_care_consultation_sessions_provider_id'), 'care_consultation_sessions', ['provider_id'], unique=False)
    op.create_index(op.f('ix_care_consultation_sessions_student_id'), 'care_consultation_sessions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_care_consultation_sessions_student_id'), table_name='care_consultation_sessions')
    op.drop_index(op.f('ix_care_consultation_sessions_provider_id'), table_name='care_consultation_sessions')
    op.drop_index(op.f('ix_care_consultation_sessions_appointment_id'), table_name='care_consultation_sessions')
    op.drop_table('care_consultation_sessions')
    op.drop_index(op.f('ix_care_intake_review_items_intake_id'), table_name='care_intake_review_items')
    op.drop_table('care_intake_review_items')
    op.drop_index(op.f('ix_care_appointments_slot_id'), table_name='care_appointments')
    op.drop_index(op.f('ix_care_appointments_provider_id'), table_name='care_appointments')
    op.drop_index(op.f('ix_care_appointments_catalog_item_id'), table_name='care_appointments')
    op.drop_index(op.f('ix_care_appointments_account_id'), table_name='care_appointments')
    op.drop_table('care_appointments')
    op.drop_index(op.f('ix_care_record_shares_owner_id'), table_name='care_record_shares')
    op.drop_index(op.f('ix_care_record_shares_document_id'), table_name='care_record_shares')
    op.drop_index(op.f('ix_care_record_shares_clinician_id'), table_name='care_record_shares')
    op.drop_table('care_record_shares')
    op.drop_index(op.f('ix_care_payments_order_id'), table_name='care_payments')
    op.drop_index(op.f('ix_care_payments_idempotency_key'), table_name='care_payments')
    op.drop_table('care_payments')
    op.drop_index(op.f('ix_care_order_lines_provider_id'), table_name='care_order_lines')
    op.drop_index(op.f('ix_care_order_lines_order_id'), table_name='care_order_lines')
    op.drop_table('care_order_lines')
    op.drop_index(op.f('ix_care_medication_doses_plan_id'), table_name='care_medication_doses')
    op.drop_index(op.f('ix_care_medication_doses_account_id'), table_name='care_medication_doses')
    op.drop_table('care_medication_doses')
    op.drop_index(op.f('ix_care_document_intake_document_id'), table_name='care_document_intake')
    op.drop_index(op.f('ix_care_document_intake_account_id'), table_name='care_document_intake')
    op.drop_table('care_document_intake')
    op.drop_index(op.f('ix_care_claim_requests_policy_id'), table_name='care_claim_requests')
    op.drop_index(op.f('ix_care_claim_requests_account_id'), table_name='care_claim_requests')
    op.drop_table('care_claim_requests')
    op.drop_index(op.f('ix_care_availability_slots_provider_id'), table_name='care_availability_slots')
    op.drop_index(op.f('ix_care_availability_slots_catalog_item_id'), table_name='care_availability_slots')
    op.drop_table('care_availability_slots')
    op.drop_index(op.f('ix_care_support_requests_account_id'), table_name='care_support_requests')
    op.drop_table('care_support_requests')
    op.drop_index(op.f('ix_care_sessions_expires_at'), table_name='care_sessions')
    op.drop_index(op.f('ix_care_sessions_account_id'), table_name='care_sessions')
    op.drop_table('care_sessions')
    op.drop_index(op.f('ix_care_readings_recorded_at'), table_name='care_readings')
    op.drop_index(op.f('ix_care_readings_metric'), table_name='care_readings')
    op.drop_index(op.f('ix_care_readings_account_id'), table_name='care_readings')
    op.drop_table('care_readings')
    op.drop_table('care_preferences')
    op.drop_index(op.f('ix_care_policies_account_id'), table_name='care_policies')
    op.drop_table('care_policies')
    op.drop_index(op.f('ix_care_orders_created_at'), table_name='care_orders')
    op.drop_index(op.f('ix_care_orders_account_id'), table_name='care_orders')
    op.drop_table('care_orders')
    op.drop_table('care_notification_preferences')
    op.drop_index(op.f('ix_care_medication_plans_account_id'), table_name='care_medication_plans')
    op.drop_table('care_medication_plans')
    op.drop_index(op.f('ix_care_health_camp_stations_camp_id'), table_name='care_health_camp_stations')
    op.drop_table('care_health_camp_stations')
    op.drop_index(op.f('ix_care_exercise_sessions_account_id'), table_name='care_exercise_sessions')
    op.drop_table('care_exercise_sessions')
    op.drop_index(op.f('ix_care_encounter_notes_patient_id'), table_name='care_encounter_notes')
    op.drop_index(op.f('ix_care_encounter_notes_appointment_id'), table_name='care_encounter_notes')
    op.drop_index(op.f('ix_care_encounter_notes_account_id'), table_name='care_encounter_notes')
    op.drop_table('care_encounter_notes')
    op.drop_index(op.f('ix_care_documents_account_id'), table_name='care_documents')
    op.drop_table('care_documents')
    op.drop_table('care_deletion_requests')
    op.drop_index(op.f('ix_care_catalog_provider_id'), table_name='care_catalog')
    op.drop_table('care_catalog')
    op.drop_table('care_campus_verifications')
    op.drop_index(op.f('ix_care_camp_attendances_camp_id'), table_name='care_camp_attendances')
    op.drop_index(op.f('ix_care_camp_attendances_account_id'), table_name='care_camp_attendances')
    op.drop_table('care_camp_attendances')
    op.drop_index(op.f('ix_care_workflow_audit_created_at'), table_name='care_workflow_audit')
    op.drop_index(op.f('ix_care_workflow_audit_actor_id'), table_name='care_workflow_audit')
    op.drop_table('care_workflow_audit')
    op.drop_table('care_system_settings')
    op.drop_table('care_signup_grants')
    op.drop_table('care_scheduled_jobs')
    op.drop_table('care_reviewed_benefits')
    op.drop_index(op.f('ix_care_rate_buckets_expires_at'), table_name='care_rate_buckets')
    op.drop_table('care_rate_buckets')
    op.drop_index(op.f('ix_care_outbox_events_dedupe_key'), table_name='care_outbox_events')
    op.drop_index(op.f('ix_care_outbox_events_account_id'), table_name='care_outbox_events')
    op.drop_table('care_outbox_events')
    op.drop_index(op.f('ix_care_otp_challenges_identifier'), table_name='care_otp_challenges')
    op.drop_table('care_otp_challenges')
    op.drop_table('care_knowledge_sources')
    op.drop_table('care_home_content')
    op.drop_table('care_health_camps')
    op.drop_index(op.f('ix_care_followup_tasks_order_id'), table_name='care_followup_tasks')
    op.drop_index(op.f('ix_care_followup_tasks_account_id'), table_name='care_followup_tasks')
    op.drop_table('care_followup_tasks')
    op.drop_table('care_articles')
    op.drop_index(op.f('ix_care_agent_runs_job_key'), table_name='care_agent_runs')
    op.drop_table('care_agent_runs')
    op.drop_index(op.f('ix_care_accounts_identifier'), table_name='care_accounts')
    op.drop_table('care_accounts')
    # ### end Alembic commands ###
