apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    name: {{ .Release.Namespace }}
    environment: {{ .Values.global.environment }}
    app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: Secret
metadata:
  name: studentkare-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.backend.secrets.DATABASE_URL | quote }}
  OTP_HASH_SECRET: {{ .Values.backend.secrets.OTP_HASH_SECRET | quote }}
  SENTRY_DSN: {{ .Values.backend.secrets.SENTRY_DSN | quote }}
  ALERTMANAGER_WEBHOOK_SECRET: {{ .Values.backend.secrets.ALERTMANAGER_WEBHOOK_SECRET | quote }}
  SLACK_WEBHOOK_URL: {{ .Values.alertmanager.config.global.slack_api_url | quote }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.grafana.adminPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | b64enc | quote }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}