import React, { useMemo, useState } from 'react';
import { Activity, ArrowRight, CheckCircle2, Download, FileText, HeartPulse, Plus, ShieldCheck, Trash2 } from 'lucide-react';
import { useApiResource } from '../../hooks/useApiResource';
import { apiFileUrl, apiRequest } from '../../data/http';
import { LiveDocument, LiveOrder, LivePolicy, LiveReading, MetricDefinition, ServiceHealth, SupportTicket, ReviewedBenefit, ClaimRequest, RecordShare, displayDate, money } from '../../data/workflowTypes';
import { DataState, EmptyState, Field, FormError, Pagination, SubmitButton, useMutation } from '../../components/interface/WorkflowUI';
import { ShopDialog } from '../../components/marketplace/ShopDialog';
import { TrendChart } from '../../components/health/HealthPrimitives';
import { navigate } from '../../lib/workflowRouting';
import { estimateCoverage } from '../../data/healthExperience';

import { HITLApprovalConsole } from '../../components/health/HITLApprovalConsole';
import { CareDashboardSummary } from '../../features/preventive/screens/CareDashboardSummary';

const localNow = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16);

export function MemberOverview() {
  const [completedTasks, setCompletedTasks] = useState<string[]>([]);
  const readings = useApiResource<{ items: LiveReading[] }>('/health/readings?days=90');
  const definitions = useApiResource<{ items: MetricDefinition[] }>('/health/metrics');
  const [metric, setMetric] = useState('heart');
  const [period, setPeriod] = useState(7);
  const [readingIndex, setReadingIndex] = useState<number | null>(null);
  const [adding, setAdding] = useState(false);
  const [formMetric, setFormMetric] = useState('heart');
  const [value, setValue] = useState('');
  const [recordedAt, setRecordedAt] = useState(localNow);
  const mutation = useMutation();
  const series = useMemo(() => (readings.data?.items || []).filter(item => item.metric === metric && new Date(item.recordedAt).getTime() >= Date.now() - period * 86400000), [readings.data, metric, period]);
  const definition = definitions.data?.items.find(item => item.id === metric);
  const formDefinition = definitions.data?.items.find(item => item.id === formMetric);
  const selectedIndex = Math.min(readingIndex ?? series.length - 1, series.length - 1);
  const point = series[selectedIndex];
  return <>
    {/* 1. Main Interactive Health & Exercise Overview Dashboard */}
    <CareDashboardSummary
      completedTasks={completedTasks}
      onToggleTask={(id) => setCompletedTasks(prev => prev.includes(id) ? prev.filter(t => t !== id) : [...prev, id])}
    />

    <section className="wf-card wf-section-gap"><div className="wf-panel-heading"><div><span className="care-eyebrow">YOUR NEXT STEP</span><h3>Vaccines, report follow-up & seasonal care.</h3><p>Compare sourced provider listings, request a clinician review, and choose your health updates.</p></div><button className="health-button" onClick={() => navigate('preventive-care')}>Open preventive care<ArrowRight size={16} /></button></div></section>

    {/* 2. Devices & Sensors — real camera/motion/voice/pulse tools with honest states */}
    <div style={{ marginTop: '24px' }}>
      <section className="wf-card">
        <div className="wf-panel-heading"><div><span className="care-eyebrow">DEVICES & SENSORS</span><h3>Real device tools, honest readings.</h3><p>Use the camera, foreground movement, voice, and pulse tools. Every reading is labelled as measured, estimated, or manual.</p></div><button className="health-button" onClick={() => navigate('devices')}><Activity size={16} />Open devices & sensors</button></div>
      </section>
    </div>

    {/* 3. Recorded Readings & Manual Entry Section */}
    <div className="wf-panel-heading" style={{ marginTop: '32px' }}><div><span className="care-eyebrow">YOUR HEALTH, FROM YOUR RECORDS</span><h2>A clearer picture of your health.</h2><p>Measurements you record appear here with their original date and source.</p></div><button className="health-button health-button-primary" onClick={() => setAdding(true)}><Plus size={16} />Record a reading</button></div>
    <DataState loading={readings.loading || definitions.loading} error={readings.error || definitions.error} retry={() => { readings.reload(); definitions.reload(); }}>
      <div className="wf-metric-grid">{definitions.data?.items.slice(0, 4).map(item => {
        const latest = readings.data?.items.filter(reading => reading.metric === item.id).slice(-1)[0];
        return <button key={item.id} className={`wf-metric-card ${metric === item.id ? 'is-selected' : ''}`} aria-pressed={metric === item.id} onClick={() => { setMetric(item.id); setReadingIndex(null); }}><span className="wf-metric-icon"><HeartPulse size={20} /></span><span>{item.label}</span><strong>{latest ? latest.value.toLocaleString('en-IN') : '—'} <small>{item.unit}</small></strong><small>{latest ? `Recorded ${displayDate(latest.recordedAt)}` : 'No measurement recorded'}</small></button>;
      })}</div>
      <section className="wf-card wf-chart-card"><div className="wf-panel-heading"><Field label="Metric"><select value={metric} onChange={event => { setMetric(event.target.value); setReadingIndex(null); }}>{definitions.data?.items.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></Field><div className="wf-choice-row" aria-label="Reading period">{[7, 30, 90].map(days => <button key={days} aria-pressed={period === days} onClick={() => { setPeriod(days); setReadingIndex(null); }}>{days} days</button>)}</div></div>
        {series.length ? <><div className="wf-chart-current"><strong>{point?.value.toLocaleString('en-IN')} <small>{definition?.unit}</small></strong><span>{point && displayDate(point.recordedAt)} · Manually recorded</span></div>{series.length > 1 ? <TrendChart key={`${metric}-${period}`} values={series.map(item => item.value)} color="#927bae" label={`${definition?.label}: ${series.length} recorded readings`} activeIndex={selectedIndex} /> : <p className="wf-notice">One reading recorded. Add another measurement to see a trend.</p>}
          <input className="wf-reading-slider" type="range" aria-label="Explore recorded readings" aria-valuetext={point ? `${displayDate(point.recordedAt)}, ${point.value} ${point.unit}` : undefined} min={0} max={Math.max(0, series.length - 1)} value={Math.max(0, selectedIndex)} onChange={event => setReadingIndex(Number(event.target.value))} />
          <details className="wf-details"><summary>View recorded values</summary><div className="wf-table-scroll"><table><thead><tr><th>Recorded</th><th>Value</th><th>Source</th><th /></tr></thead><tbody>{series.map(item => <tr key={item.id}><td>{displayDate(item.recordedAt)}</td><td>{item.value} {item.unit}</td><td>Manual entry</td><td><button className="wf-icon-button" aria-label={`Delete reading from ${displayDate(item.recordedAt)}`} disabled={mutation.busy} onClick={() => mutation.run(() => apiRequest(`/health/readings/${item.id}`, { method: 'DELETE' }), readings.reload)}><Trash2 size={15} /></button></td></tr>)}</tbody></table></div></details>
        </> : <EmptyState title="Your readings start here." description="There are no recorded measurements for this metric in the selected period. Values will never be invented to fill the chart." action="Record a reading" onAction={() => { setFormMetric(metric); setAdding(true); }} />}
        <FormError message={!adding ? mutation.error : ''} />
      </section>
      <section className="wf-movement-card"><Activity size={28} /><div><h3>Make space for everyday movement.</h3><p>Explore source-linked exercise guides and keep your own session history.</p></div><button className="health-button" onClick={() => navigate('movement')}>Explore movement <ArrowRight size={15} /></button></section>
      <div className="wf-two-column"><button className="wf-navigation-card" onClick={() => navigate('records')}><FileText size={24} /><strong>Your records, together.</strong><span>Upload and retrieve your own reports and prescriptions.</span><ArrowRight size={18} /></button><button className="wf-navigation-card wf-navigation-mint" onClick={() => navigate('insurance')}><ShieldCheck size={24} /><strong>Keep your cover in view.</strong><span>Record policy details and find support with your next steps.</span><ArrowRight size={18} /></button></div>
    </DataState>
    {adding && <ShopDialog title="Record a health reading" onClose={() => setAdding(false)}><form className="wf-form" onSubmit={event => { event.preventDefault(); mutation.run(() => apiRequest('/health/readings', { method: 'POST', body: JSON.stringify({ metric: formMetric, value: Number(value), recordedAt: new Date(recordedAt).toISOString() }) }), () => { setAdding(false); setValue(''); readings.reload(); }); }}><p>Enter a measurement from your device or report. The app does not estimate these readings.</p><FormError message={mutation.error} /><Field label="Metric"><select value={formMetric} onChange={event => { setFormMetric(event.target.value); setValue(''); }}>{definitions.data?.items.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></Field><Field label={`Value (${formDefinition?.unit || ''})`}><input required type="number" step={formMetric === 'steps' ? '1' : 'any'} min={formDefinition?.min} max={formDefinition?.max} value={value} onChange={event => setValue(event.target.value)} /></Field><Field label="Date and time measured"><input required type="datetime-local" value={recordedAt} onChange={event => setRecordedAt(event.target.value)} /></Field><SubmitButton busy={mutation.busy}>Save reading</SubmitButton></form></ShopDialog>}
  </>;
}

export function RecordsPanel() {
  const [page, setPage] = useState(0);
  const resource = useApiResource<{ items: LiveDocument[]; total?: number }>(`/health/documents?limit=12&offset=${page * 12}`);
  const shares = useApiResource<{ items: RecordShare[] }>('/records/shares');
  const [adding, setAdding] = useState(false);
  const [shareOpen, setShareOpen] = useState(false);
  const [shareDoc, setShareDoc] = useState('');
  const [shareClinician, setShareClinician] = useState('');
  const [shareDays, setShareDays] = useState('7');
  const [deleteNotice, setDeleteNotice] = useState('');
  const [title, setTitle] = useState('');
  const [category, setCategory] = useState('LAB');
  const [file, setFile] = useState<File | null>(null);
  const mutation = useMutation();
  const shareMutation = useMutation();
  const exportMutation = useMutation();
  const doExport = () => { exportMutation.run(async () => { const res = await apiRequest<{ user: any; documents: any[]; readings: any[]; policies: any[] }>('/records/export'); const blob = new Blob([JSON.stringify(res, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'studentkare-export.json'; a.click(); URL.revokeObjectURL(url); }); };
  return <>
    <section className="wf-card wf-section-gap"><div className="wf-panel-heading"><div><h3>Need help understanding a report?</h3><p>Share the report with your clinician, then request a reviewed summary and next steps.</p></div><button className="health-button" onClick={() => navigate('preventive-care')}>Report follow-up<ArrowRight size={16} /></button></div></section>
    <div className="wf-panel-heading"><div><span className="care-eyebrow">YOUR PERSONAL HEALTH VAULT</span><h2>Every record has a place.</h2><p>Your uploads are retrieved from your account. Only you can access these files.</p></div><button className="health-button health-button-primary" onClick={() => setAdding(true)}><Plus size={16} />Upload a record</button></div>
    <DataState {...resource} retry={resource.reload}>{resource.data?.items.length ? <><div className="wf-record-grid">{resource.data.items.map(item => <article className="wf-card" key={item.id}><span className="wf-record-icon"><FileText size={24} /></span><span className="wf-status">{item.category.replace(/_/g, ' ')}</span><h3>{item.title}</h3><p>{item.filename}</p><small>Uploaded {displayDate(item.createdAt)}</small><div className="wf-row-actions"><a className="health-button" href={apiFileUrl(item.id)} download><Download size={14} />Download</a><button className="health-button" onClick={() => { setShareDoc(item.id); setShareOpen(true); }}><ShieldCheck size={14} />Share</button><button className="wf-icon-button" disabled={mutation.busy} aria-label={`Delete ${item.title}`} onClick={() => mutation.run(() => apiRequest(`/health/documents/${item.id}`, { method: 'DELETE' }), resource.reload)}><Trash2 size={16} /></button></div></article>)}</div><Pagination page={page} total={resource.data?.total || resource.data.items.length} pageSize={12} onChange={setPage} /></> : <EmptyState title="Your vault is ready." description="Upload a report, prescription, or vaccination record. No sample records have been added to your account." action="Upload a record" onAction={() => setAdding(true)} />}</DataState>
    <FormError message={!adding ? mutation.error : ''} />
    <section className="wf-card wf-section-gap"><div className="wf-panel-heading"><div><span className="care-eyebrow">YOUR DATA, YOUR CONTROL</span><h3>Privacy & access</h3><p>Export your records, review clinician access, or request deletion.</p></div><div className="wf-row-actions"><button className="health-button" disabled={exportMutation.busy} onClick={doExport}><Download size={16} />{exportMutation.busy ? 'Preparing…' : 'Export my data'}</button></div></div>
      <DataState {...shares} retry={shares.reload}>{shares.data?.items.length ? <div className="wf-order-list">{shares.data.items.map(share => <div className="wf-order-line" key={share.id}><div><strong>{share.clinician}</strong><small>{share.document} · {share.active ? `expires ${displayDate(share.expiresAt)}` : share.revoked ? 'revoked' : 'expired'}</small></div><span className={`wf-status ${share.active ? 'status-accepted' : 'status-declined'}`}>{share.active ? 'Active' : share.revoked ? 'Revoked' : 'Expired'}</span>{share.active && <button className="health-text-button" disabled={shareMutation.busy} onClick={() => shareMutation.run(() => apiRequest(`/records/shares/${share.id}/revoke`, { method: 'POST' }), shares.reload)}>Revoke</button>}</div>)}</div> : <EmptyState title="No shared records." description="When you grant a clinician access to a record, it appears here with an expiry." />}</DataState>
      <div className="wf-two-column wf-section-gap"><div className="wf-notice"><ShieldCheck size={18} />Sharing gives a clinician time-limited view of one record. It is revocable and expires automatically.</div><button className="health-button" onClick={() => { setDeleteNotice(''); mutation.run(() => apiRequest('/records/deletion-request', { method: 'POST' }), () => setDeleteNotice('Deletion request recorded. This is a pending request, not immediate removal.')); }}>Request data deletion</button></div>
      {deleteNotice && <div className="wf-notice" role="status" style={{ marginTop: 14, background: '#ecfdf5', color: '#065f46', borderColor: '#a7f3d0' }}><CheckCircle2 size={18} />{deleteNotice}</div>}
    </section>
    {adding && <ShopDialog title="Upload a health record" onClose={() => setAdding(false)}><form className="wf-form" onSubmit={event => { event.preventDefault(); if (!file) return; const form = new FormData(); form.append('title', title); form.append('category', category); form.append('file', file); mutation.run(() => apiRequest('/health/documents', { method: 'POST', body: form }), () => { setAdding(false); setTitle(''); setFile(null); resource.reload(); }); }}><FormError message={mutation.error} /><Field label="Record title"><input required maxLength={160} value={title} onChange={event => setTitle(event.target.value)} /></Field><Field label="Record category"><select value={category} onChange={event => setCategory(event.target.value)}>{['LAB', 'PRESCRIPTION', 'VACCINE', 'CAMP_REPORT', 'DISCHARGE_SUMMARY', 'OTHER'].map(value => <option key={value}>{value}</option>)}</select></Field><Field label="File" hint="PDF, PNG, or JPEG · maximum 10 MB"><input type="file" required accept="application/pdf,image/png,image/jpeg" onChange={event => setFile(event.target.files?.[0] || null)} /></Field><p className="wf-fineprint">Uploading a prescription saves the document. It does not perform a pharmacy review or authorise dispensing.</p><SubmitButton busy={mutation.busy}>Save record</SubmitButton></form></ShopDialog>}
    {shareOpen && <ShopDialog title="Share a record" onClose={() => setShareOpen(false)}><form className="wf-form" onSubmit={event => { event.preventDefault(); shareMutation.run(() => apiRequest('/records/shares', { method: 'POST', body: JSON.stringify({ documentId: shareDoc, clinicianEmail: shareClinician, expiresInDays: Number(shareDays) }) }), () => { setShareOpen(false); shares.reload(); }); }}><p>Grant a clinician time-limited access to this record. You can revoke it any time.</p><FormError message={shareMutation.error} /><Field label="Clinician email"><input required type="email" value={shareClinician} onChange={event => setShareClinician(event.target.value)} /></Field><Field label="Access expires (days)"><input required type="number" min="1" max="90" value={shareDays} onChange={event => setShareDays(event.target.value)} /></Field><SubmitButton busy={shareMutation.busy}>Grant access</SubmitButton></form></ShopDialog>}
  </>;
}

export function OrdersPanel() {
  const [page, setPage] = useState(0);
  const resource = useApiResource<{ items: LiveOrder[]; total?: number }>(`/orders?limit=10&offset=${page * 10}`);
  const mutation = useMutation();
  return <><div className="wf-panel-heading"><div><span className="care-eyebrow">CARE THAT YOU CAN FOLLOW</span><h2>Your orders & service requests.</h2><p>Requested appointments become confirmed only after a provider accepts them.</p></div><button className="health-button" onClick={() => navigate('shop')}>Explore services <ArrowRight size={15} /></button></div><FormError message={mutation.error} /><DataState {...resource} retry={resource.reload}>{resource.data?.items.length ? <><div className="wf-order-list">{resource.data.items.map(order => <article className="wf-card wf-order" key={order.id}><div className="wf-panel-heading"><div><span className="care-eyebrow">REQUEST {order.id.slice(0, 8).toUpperCase()}</span><h3>{displayDate(order.createdAt)}</h3></div><strong>{money(order.totalPaise)}</strong></div>{order.lines.map(line => <div className="wf-order-line" key={line.id}><div><strong>{line.name}</strong><small>{line.quantity} × {money(line.pricePaise)}</small></div><span className={`wf-status status-${line.status.toLowerCase()}`}>{line.status.replace(/_/g, ' ')}</span></div>)}<div className="wf-order-meta"><span>{order.delivery.mode === 'pickup' ? 'Provider pickup' : order.delivery.address} · {order.delivery.city}</span>{order.requestedSlot && <span>Requested time: {displayDate(order.requestedSlot)}</span>}<span>Payment: <strong>{order.paymentStatus === 'PAID' ? 'Paid' : 'Unpaid — arranged with provider'}</strong></span><small>No online payment has been collected unless a payment provider is connected.</small></div>{order.lines.every(line => line.status === 'REQUESTED') && <button className="health-text-button" disabled={mutation.busy} onClick={() => mutation.run(() => apiRequest(`/orders/${order.id}/cancel`, { method: 'POST' }), resource.reload)}>Cancel this request</button>}</article>)}</div><Pagination page={page} total={resource.data?.total || resource.data.items.length} pageSize={10} onChange={setPage} /></> : <EmptyState title="No requests yet." description="Requests you submit from the catalog will appear here with updates from the assigned provider." />}</DataState></>;
}

export function InsurancePanel() {
  const resource = useApiResource<{ items: LivePolicy[] }>('/health/policies');
  const benefits = useApiResource<{ items: ReviewedBenefit[] }>('/insurance/benefits');
  const claims = useApiResource<{ items: ClaimRequest[] }>('/insurance/claims');
  const [adding, setAdding] = useState(false);
  const [claiming, setClaiming] = useState(false);
  const [claimPolicy, setClaimPolicy] = useState('');
  const [claimProvider, setClaimProvider] = useState('');
  const [claimService, setClaimService] = useState('');
  const [claimAmount, setClaimAmount] = useState('');
  const [claimNotice, setClaimNotice] = useState('');
  const [eligibility, setEligibility] = useState<string>('');
  const [insurer, setInsurer] = useState('');
  const [number, setNumber] = useState('');
  const [sum, setSum] = useState('');
  const [until, setUntil] = useState('');
  const [bill, setBill] = useState('');
  const [excluded, setExcluded] = useState('');
  const [copay, setCopay] = useState('');
  const [remaining, setRemaining] = useState('');
  const mutation = useMutation();
  const claimMutation = useMutation();
  const estimate = [bill, excluded, copay, remaining].every(value => value.trim() !== '') ? estimateCoverage(Number(bill), Number(excluded), { remainingCover: Number(remaining), copayPercent: Number(copay) }) : null;
  const categories = Array.from(new Set(benefits.data?.items.map(b => b.category) || []));
  return <><div className="wf-panel-heading"><div><span className="care-eyebrow">YOUR COVER, CLEARLY RECORDED</span><h2>Insurance & policy information.</h2><p>Keep details from your policy documents in one place.</p></div><div className="wf-row-actions"><button className="health-button" onClick={() => setClaiming(true)}>Prepare a claim request</button><button className="health-button health-button-primary" onClick={() => setAdding(true)}><Plus size={15} />Add policy details</button></div></div>
  <div className="wf-record-grid" style={{ marginBottom: 24 }}>{categories.length ? categories.map(category => <section className="wf-card" key={category}><span className="care-eyebrow">{category.replace(/-/g, ' ')}</span>{benefits.data?.items.filter(b => b.category === category).map(b => <div key={b.id} style={{ padding: '10px 0', borderBottom: '1px solid var(--rule-soft)' }}><h3 style={{ fontSize: 14 }}>{b.title}</h3><p style={{ fontSize: 12 }}>{b.description}</p></div>)}</section>) : <EmptyState title="Benefit directory is loading." description="Reviewed coverage summaries appear here once available." />}</div>
  <DataState {...resource} retry={resource.reload}>{resource.data?.items.length ? <div className="wf-record-grid">{resource.data.items.map(policy => <article className="wf-card wf-policy" key={policy.id}><ShieldCheck size={28} /><span className="wf-status">User-recorded · not insurer verified</span><h3>{policy.insurer}</h3><p>{policy.policyNumber}</p><strong className="wf-large-value">{money(policy.sumInsured * 100)}</strong><small>Recorded sum insured · Valid until {policy.validUntil}</small><div className="wf-row-actions"><button className="health-button" disabled={mutation.busy} onClick={() => mutation.run(() => apiRequest<{ configured: boolean; status: string; message: string }>(`/insurance/eligibility?policyId=${encodeURIComponent(policy.id)}`), (res) => setEligibility(res.message))}>Check eligibility</button><button className="health-text-button" disabled={mutation.busy} onClick={() => mutation.run(() => apiRequest(`/health/policies/${policy.id}`, { method: 'DELETE' }), resource.reload)}>Remove policy details</button></div>{eligibility && <div className="wf-notice" role="status" style={{ marginTop: 10, background: '#fef3c7', color: '#92400e', borderColor: '#fde68a' }}><ShieldCheck size={18} />{eligibility}</div>}</article>)}</div> : <EmptyState title="No policy has been recorded." description="Add details from a policy you already hold. Adding information does not purchase or activate insurance." />}</DataState><FormError message={!adding ? mutation.error : ''} />
      <div className="wf-two-column wf-section-gap"><section className="wf-card"><span className="care-eyebrow">UNDERSTAND THE NUMBERS YOU ENTER</span><h3>Out-of-pocket calculator</h3><p>Use your actual policy terms and remaining cover. This calculation is not an insurer decision.</p><div className="wf-form-grid">{[{ label: 'Medical bill (₹)', value: bill, set: setBill }, { label: 'Non-covered expenses (₹)', value: excluded, set: setExcluded }, { label: 'Co-pay (%)', value: copay, set: setCopay }, { label: 'Remaining cover (₹)', value: remaining, set: setRemaining }].map(field => <Field key={field.label} label={field.label}><input type="number" min="0" step="any" value={field.value} onChange={event => field.set(event.target.value)} /></Field>)}</div><div className="wf-calculator-result" aria-live="polite"><span>Estimated insurer share<strong>{estimate ? money(Math.round(estimate.covered * 100)) : '—'}</strong></span><span>Estimated out-of-pocket<strong>{estimate ? money(Math.round(estimate.outOfPocket * 100)) : '—'}</strong></span></div>{[bill, excluded, copay, remaining].every(Boolean) && !estimate && <p className="wf-form-message">Check your amounts: exclusions cannot exceed the bill and co-pay must be between 0 and 100%.</p>}</section><section className="wf-card wf-integration-note"><ShieldCheck size={30} /><h3>Insurer services are not connected.</h3><p>Live eligibility, cashless authorisation, and claim submission are unavailable until an insurer integration is configured. No claim is submitted by this screen.</p><button className="health-button" onClick={() => navigate('support')}>Contact support <ArrowRight size={15} /></button></section></div>
      <section className="wf-card wf-section-gap"><div className="wf-panel-heading"><div><span className="care-eyebrow">YOUR CLAIM REQUESTS</span><h3>Prepared claim requests</h3><p>These are drafts for your records. They are not insurer submissions.</p></div></div><DataState {...claims} retry={claims.reload}>{claims.data?.items.length ? <div className="wf-order-list">{claims.data.items.map(claim => <div className="wf-order-line" key={claim.id}><div><strong>{claim.service || 'Claim request'}</strong><small>{claim.providerName || 'Provider'} · {money(claim.amountPaise)} · {displayDate(claim.createdAt)}</small></div><div className="wf-row-actions"><span className="wf-status status-requested">{claim.status}</span>{claim.status === 'DRAFT' && <button className="health-button" disabled={claimMutation.busy} onClick={() => claimMutation.run(() => apiRequest(`/insurance/claims/${claim.id}/submit`, { method: 'POST' }), (res) => { setClaimNotice((res as any)?.submitted === false ? (res as any).message : 'Claim submitted.'); claims.reload(); })}>Submit to insurer</button>}</div></div>)}</div> : <EmptyState title="No claim requests yet." description="Prepare a claim request for your records. It is not submitted to an insurer." action="Prepare a claim request" onAction={() => setClaiming(true)} />}</DataState>{claimNotice && <div className="wf-notice" role="status" style={{ marginTop: 12, background: '#fef3c7', color: '#92400e', borderColor: '#fde68a' }}><ShieldCheck size={18} />{claimNotice}</div>}</section>
      {adding && <ShopDialog title="Record your policy details" onClose={() => setAdding(false)}><form className="wf-form" onSubmit={event => { event.preventDefault(); mutation.run(() => apiRequest('/health/policies', { method: 'POST', body: JSON.stringify({ insurer, policyNumber: number, sumInsured: Number(sum), validUntil: until }) }), () => { setAdding(false); resource.reload(); }); }}><FormError message={mutation.error} /><Field label="Insurer"><input required minLength={2} maxLength={100} value={insurer} onChange={event => setInsurer(event.target.value)} /></Field><Field label="Policy number"><input required minLength={2} maxLength={100} value={number} onChange={event => setNumber(event.target.value)} /></Field><Field label="Sum insured (₹)"><input required type="number" min="1" max="100000000" value={sum} onChange={event => setSum(event.target.value)} /></Field><Field label="Valid until"><input required type="date" value={until} onChange={event => setUntil(event.target.value)} /></Field><SubmitButton busy={mutation.busy}>Save policy details</SubmitButton></form></ShopDialog>}
      {adding && <ShopDialog title="Record your policy details" onClose={() => setAdding(false)}><form className="wf-form" onSubmit={event => { event.preventDefault(); mutation.run(() => apiRequest('/health/policies', { method: 'POST', body: JSON.stringify({ insurer, policyNumber: number, sumInsured: Number(sum), validUntil: until }) }), () => { setAdding(false); resource.reload(); }); }}><FormError message={mutation.error} /><Field label="Insurer"><input required minLength={2} maxLength={100} value={insurer} onChange={event => setInsurer(event.target.value)} /></Field><Field label="Policy number"><input required minLength={2} maxLength={100} value={number} onChange={event => setNumber(event.target.value)} /></Field><Field label="Sum insured (₹)"><input required type="number" min="1" max="100000000" value={sum} onChange={event => setSum(event.target.value)} /></Field><Field label="Valid until"><input required type="date" value={until} onChange={event => setUntil(event.target.value)} /></Field><SubmitButton busy={mutation.busy}>Save policy details</SubmitButton></form></ShopDialog>}
      {claiming && <ShopDialog title="Prepare a claim request" onClose={() => setClaiming(false)}><form className="wf-form" onSubmit={event => { event.preventDefault(); claimMutation.run(() => apiRequest('/insurance/claims', { method: 'POST', body: JSON.stringify({ policyId: claimPolicy, providerName: claimProvider, service: claimService, amountPaise: Math.round(Number(claimAmount) * 100) }) }), () => { setClaiming(false); claims.reload(); }); }}><p>Save a draft of an expense you intend to claim. This is not submitted to an insurer.</p><FormError message={claimMutation.error} /><Field label="Policy"><select required value={claimPolicy} onChange={event => setClaimPolicy(event.target.value)}><option value="">Choose a policy…</option>{resource.data?.items.map(policy => <option key={policy.id} value={policy.id}>{policy.insurer} · {policy.policyNumber}</option>)}</select></Field><Field label="Provider / hospital"><input value={claimProvider} maxLength={160} onChange={event => setClaimProvider(event.target.value)} /></Field><Field label="Service"><input value={claimService} maxLength={160} onChange={event => setClaimService(event.target.value)} /></Field><Field label="Amount (₹)"><input required type="number" min="1" step="any" value={claimAmount} onChange={event => setClaimAmount(event.target.value)} /></Field><SubmitButton busy={claimMutation.busy}>Save claim request</SubmitButton></form></ShopDialog>}
  </>;
}

export function SupportPanel({ staff = false }: { staff?: boolean }) {
  const resource = useApiResource<{ items: SupportTicket[] }>('/support');
  const [subject, setSubject] = useState('');
  const [message, setMessage] = useState('');
  const [notice, setNotice] = useState('');
  const mutation = useMutation();
  return <><div className="wf-panel-heading"><div><span className="care-eyebrow">A LITTLE HELP WITH YOUR NEXT STEP</span><h2>{staff ? 'Support requests' : 'How can we help?'}</h2><p>{staff ? 'Requests submitted by account holders.' : 'Send an account or service enquiry to the platform team.'}</p></div></div>
  <FormError message={mutation.error} />
  {!staff && <div className="wf-points-banner" style={{ background: 'linear-gradient(135deg, #f3e8ff, #ede9fe)', border: '1px solid #ddd6fe', padding: '12px 16px', borderRadius: '12px', marginBottom: '16px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '10px' }}><span>🪙 <strong>Earn +50 Care Points</strong> for every support request submitted and resolved.</span><span style={{ fontSize: '11px', fontWeight: 700, color: '#7c3aed', background: '#ffffff', padding: '4px 10px', borderRadius: '14px', border: '1px solid #c4b5fd', whiteSpace: 'nowrap' }}>+50 PTS / TICKET</span></div>}
  {notice && <div className="wf-notice" style={{ background: '#ecfdf5', color: '#065f46', borderColor: '#a7f3d0', marginBottom: '16px' }}>{notice}</div>}
  {!staff && <form className="wf-card wf-form" onSubmit={event => { event.preventDefault(); mutation.run(() => apiRequest('/support', { method: 'POST', body: JSON.stringify({ subject, message }) }), () => { setNotice('🎉 Support ticket submitted! +50 Care Points will be credited upon completion.'); setSubject(''); setMessage(''); resource.reload(); }); }}><Field label="Subject"><input required minLength={3} maxLength={160} value={subject} onChange={event => setSubject(event.target.value)} /></Field><Field label="Message"><textarea required minLength={10} maxLength={2000} rows={4} value={message} onChange={event => setMessage(event.target.value)} /></Field><SubmitButton busy={mutation.busy}>Send support request</SubmitButton></form>}
  <DataState {...resource} retry={resource.reload}>{resource.data?.items.length ? <div className="wf-order-list wf-section-gap">{resource.data.items.map(ticket => <article className="wf-card" key={ticket.id}><div className="wf-panel-heading"><div><h3>{ticket.subject}</h3><span style={{ display: 'inline-block', marginTop: '6px', fontSize: '11px', fontWeight: 700, color: ticket.status === 'RESOLVED' ? '#059669' : '#7c3aed', background: ticket.status === 'RESOLVED' ? '#ecfdf5' : '#f5f3ff', border: `1px solid ${ticket.status === 'RESOLVED' ? '#a7f3d0' : '#ddd6fe'}`, padding: '3px 9px', borderRadius: '12px' }}>{ticket.status === 'RESOLVED' ? '✨ +50 Care Points Earned' : '🪙 +50 Care Points Pending'}</span></div><span className="wf-status">{ticket.status}</span></div><p>{ticket.message}</p><small>{displayDate(ticket.createdAt)}</small>{staff && ticket.status === 'OPEN' && <button className="health-button" disabled={mutation.busy} onClick={() => mutation.run(() => apiRequest(`/ops/support/${ticket.id}`, { method: 'PATCH' }), resource.reload)}>Mark resolved</button>}</article>)}</div> : <EmptyState title="No support requests." description="Submitted requests and their status will appear here." />}</DataState></>;
}

export function IntegrationsPanel() {
  const resource = useApiResource<ServiceHealth>('/health');
  return <><div className="wf-panel-heading"><div><span className="care-eyebrow">ACTUAL SERVICE AVAILABILITY</span><h2>Connected services & AI Approvals.</h2><p>Status reflects configured capabilities, active AI agents, and clinician sign-off gates.</p></div></div>
  <div style={{ marginBottom: 20 }}>
    <HITLApprovalConsole />
  </div>
  <DataState {...resource} retry={resource.reload}><div className="wf-record-grid">{resource.data && [{ name: 'Verification delivery', available: resource.data.integrations.otpChannels.length > 0, detail: resource.data.integrations.otpChannels.join(', ') || 'Configure SMTP, Postal, or OpenWA.' }, { name: 'Persistent storage', available: resource.data.persistent, detail: 'Account data and workflow requests are stored in the configured database.' }, { name: 'Online payments', available: resource.data.integrations.payments, detail: 'No payment provider is connected. Orders are requests, not paid purchases.' }, { name: 'Insurer integration', available: resource.data.integrations.insurer, detail: 'Eligibility checks and claim submission are not connected.' }, { name: 'Device synchronisation', available: resource.data.integrations.deviceSync, detail: 'Measurements can be recorded manually. Device sync is not connected.' }, { name: 'Prescription review', available: resource.data.integrations.prescriptionReview, detail: 'Documents can be stored privately. Automatic review and dispensing are not connected.' }].map(item => <article key={item.name} className="wf-card"><span className={`wf-status ${item.available ? 'status-completed' : ''}`}>{item.available ? 'Configured' : 'Not connected'}</span><h3>{item.name}</h3><p>{item.detail}</p></article>)}</div></DataState></>;
}
